name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
  name: Deploy to VPS
  runs-on: ubuntu-22.04
  steps:
    - name: Deploy
    uses: appleboy/ssh-action@v0.1.8
    with:
      host: 161.22.45.252
      port: 2222
      username: navet21
      key: ${{secrets.PRIVATE_KEY}}
      script: "cd /var/www/html/a4.-deployingalaravelapponvps; git pull origin main; npm run build"